#include <camkes.h>
#include <stdio.h>
#include <stdint.h>
#include <lean/lean.h>
#include "darm_shim.h"

// Declare external Lean runtime initialization functions generated by Lake
extern lean_obj_res initialize_DarmMonitor_Fixed64Evaluator(lean_obj_handle);
extern lean_obj_res initialize_DarmMonitor_Fixed64Tower(lean_obj_handle);

// Declare external Lean evaluator entry point (mangled Lean symbol name pattern)
// Lean function: DarmMonitor.Fixed64Evaluator.evaluator_sound_tower64 (or equivalent core function)
extern lean_object* l_DarmMonitor_Fixed64Evaluator_evaluatorSoundTower64(lean_object*);

static int lean_runtime_initialized = 0;

static void ensure_lean_initialized(void) {
    if (!lean_runtime_initialized) {
        // Initialize Lean runtime memory allocator and thread state
        lean_initialize();
        
        // Execute module initializers generated by the Lean compiler
        lean_object* w = lean_io_mk_world();
        w = initialize_DarmMonitor_Fixed64Tower(w);
        w = initialize_DarmMonitor_Fixed64Evaluator(w);
        lean_dec_ref(w);
        
        lean_runtime_initialized = 1;
        printf("[DARM MONITOR] Lean 4 verified runtime initialized successfully.\n");
    }
}

/**
 * @brief CAmkES RPC handler for incoming untrusted AI actuation commands.
 * Intercepts calls on the `monitor_ep` interface and executes verified Lean 4 bounds.
 */
uint64_t monitor_ep_evaluate_actuation(uint64_t raw_payload) {
    ensure_lean_initialized();

    // 1. Box raw scalar payload into a Lean 64-bit integer object (or pass unboxed if optimized)
    lean_object* lean_arg = lean_box_uint64(raw_payload);

    // 2. Invoke formally verified Lean evaluator function
    lean_object* lean_res = l_DarmMonitor_Fixed64Evaluator_evaluatorSoundTower64(lean_arg);

    // 3. Unbox or extract validated result from Lean runtime object
    uint64_t validated_payload = lean_unbox_uint64(lean_res);
    lean_dec(lean_res); // Clean up reference count

    if (validated_payload == 0x0ULL && raw_payload != 0x0ULL) {
        printf("[DARM MONITOR] ALERT: Boundary violation detected by Lean proofs! Blocked payload 0x%016lX\n", 
               (unsigned long)raw_payload);
        return 0x0ULL;
    }

    printf("[DARM MONITOR] Boundary check PASSED via Lean proof towers. Dispatching payload 0x%016lX to HardwareActuator.\n",
           (unsigned long)validated_payload);
    
    return actuator_ep_dispatch(validated_payload);
}
