import GRBS

namespace GRBS
namespace E13AdversarialBoundary

/--
E13: Adversarial Boundary Completeness

The adversary is deliberately unrestricted. Its strategy is simply a
state-dependent choice of an action/effect.
-/
abbrev Strategy (State Action : Type) :=
  State → Action

/--
A semantic transition induced by an action.
-/
abbrev Transition (State Action : Type) :=
  State → Action → State → Prop

/--
The protected semantic property.
-/
abbrev SafeState (State : Type) :=
  State → Prop

/--
The boundary authorizes a transition.
-/
abbrev Authorized
    (State Action : Type) :=
  State → Action → State → Prop

/--
Every transition the adversary can cause is mediated by the boundary.
This is the first form of complete mediation.

The quantification is over arbitrary strategies. No restriction is
placed on how the strategy chooses its action.
-/
def CompleteMediation
    {State Action : Type}
    (step : Transition State Action)
    (authorized : Authorized State Action) : Prop :=
  ∀ (σ : Strategy State Action)
    (s s' : State),
    step s (σ s) s' →
    authorized s (σ s) s'

/--
Boundary soundness:

every authorized transition preserves the protected state property.
-/
def BoundarySound
    {State Action : Type}
    (step : Transition State Action)
    (authorized : Authorized State Action)
    (safe : SafeState State) : Prop :=
  ∀ s a s',
    safe s →
    authorized s a s' →
    step s a s' →
    safe s'

/--
Initial safety.
-/
def InitialSafe
    {State : Type}
    (safe : SafeState State)
    (s₀ : State) : Prop :=
  safe s₀

/--
The E13 target:

an arbitrary adversarial strategy cannot produce an unsafe
one-step transition when every strategy-induced transition is
completely mediated and the boundary is sound.
-/
theorem adversary_independent_one_step
    {State Action : Type}
    (step : Transition State Action)
    (authorized : Authorized State Action)
    (safe : SafeState State)
    (s₀ : State)
    (σ : Strategy State Action)
    (s₁ : State)
    (hInitial : InitialSafe safe s₀)
    (hMediation : CompleteMediation step authorized)
    (hBoundary : BoundarySound step authorized safe)
    (hStep : step s₀ (σ s₀) s₁) :
    safe s₁ := by
  apply hBoundary s₀ (σ s₀) s₁ hInitial
  · exact hMediation σ s₀ s₁ hStep
  · exact hStep

/--
A system can have a sound boundary for authorized transitions while
an adversary escapes it through an unmediated transition.
-/
theorem no_complete_mediation_allows_bypass :
    ∃ (State Action : Type)
      (step : Transition State Action)
      (authorized : Authorized State Action)
      (safe : SafeState State)
      (s₀ s₁ : State)
      (σ : Strategy State Action),
      safe s₀ ∧
      step s₀ (σ s₀) s₁ ∧
      ¬ safe s₁ ∧
      ¬ CompleteMediation step authorized := by

  let State := Bool
  let Action := Bool

  let step : Transition State Action :=
    fun s a s' =>
      s = false ∧ a = true ∧ s' = true

  let authorized : Authorized State Action :=
    fun _ a _ => a = false

  let safe : SafeState State :=
    fun s => s = false

  let σ : Strategy State Action :=
    fun _ => true

  refine ⟨
    State,
    Action,
    step,
    authorized,
    safe,
    false,
    true,
    σ,
    ?_,
    ?_,
    ?_,
    ?_⟩

  · rfl

  · constructor
    · rfl
    · constructor
      · rfl
      · rfl

  · simp [safe]

  · intro hComplete
    have h :=
      hComplete σ false true
        (by
          constructor
          · rfl
          · constructor <;> rfl)
    simp [authorized] at h

end E13AdversarialBoundary
end GRBS

namespace GRBS
namespace E13AdversarialBoundary

/-- A finite execution trace generated by repeatedly applying an adversarial strategy. -/
inductive Executes
    {State Action : Type}
    (step : Transition State Action)
    (σ : Strategy State Action) :
    State → Nat → State → Prop
  | zero (s : State) :
      Executes step σ s 0 s
  | succ {s s' s'' : State} {n : Nat} :
      Executes step σ s n s' →
      step s' (σ s') s'' →
      Executes step σ s (n + 1) s''

/-- Safety is preserved over every finite adversarial execution. -/
theorem adversary_independent_trace_safety
    {State Action : Type}
    (step : Transition State Action)
    (authorized : Authorized State Action)
    (safe : SafeState State)
    (s₀ : State)
    (σ : Strategy State Action)
    (n : Nat)
    (sₙ : State)
    (hInitial : InitialSafe safe s₀)
    (hMediation : CompleteMediation step authorized)
    (hBoundary : BoundarySound step authorized safe)
    (hExec : Executes step σ s₀ n sₙ) :
    safe sₙ := by
  induction hExec with
  | zero =>
      exact hInitial
  | succ hPrefix hStep ih =>
      exact hBoundary _ _ _ ih
        (hMediation _ _ _ hStep)
        hStep

/-- A mediated boundary blocks the adversary at every step of a finite trace. -/
theorem complete_mediation_blocks_unsafe_trace
    {State Action : Type}
    (step : Transition State Action)
    (authorized : Authorized State Action)
    (safe : SafeState State)
    (s₀ : State)
    (σ : Strategy State Action)
    (n : Nat)
    (sₙ : State)
    (hInitial : InitialSafe safe s₀)
    (hMediation : CompleteMediation step authorized)
    (hBoundary : BoundarySound step authorized safe)
    (hExec : Executes step σ s₀ n sₙ) :
    safe sₙ :=
  adversary_independent_trace_safety
    step authorized safe s₀ σ n sₙ
    hInitial hMediation hBoundary hExec

end E13AdversarialBoundary
end GRBS

namespace GRBS
namespace E13AdversarialBoundary

/--
E13.2 separates the transition relation governed by the boundary from
additional effects that an adversary may induce outside that relation.
-/
abbrev ExternalTransition (State : Type) := State → State → Prop

/--
The local DARM theorem can remain valid while an external transition
reaches an unsafe state. This demonstrates that boundary soundness for
the governed transition relation does not by itself establish safety
over a larger effect space.
-/
theorem local_boundary_does_not_cover_external_transition :
    ∃ (State Action : Type)
      (step : Transition State Action)
      (authorized : Authorized State Action)
      (safe : SafeState State)
      (externalStep : ExternalTransition State)
      (s₀ s₁ : State)
      (σ : Strategy State Action),
      InitialSafe safe s₀ ∧
      CompleteMediation step authorized ∧
      BoundarySound step authorized safe ∧
      externalStep s₀ s₁ ∧
      ¬ safe s₁ := by
  let State := Bool
  let Action := Bool

  let step : Transition State Action :=
    fun _ _ _ => False

  let authorized : Authorized State Action :=
    fun _ _ _ => False

  let safe : SafeState State :=
    fun s => s = false

  let externalStep : ExternalTransition State :=
    fun s s' =>
      s = false ∧ s' = true

  let σ : Strategy State Action :=
    fun _ => false

  refine
    ⟨State, Action, step, authorized, safe, externalStep,
      false, true, σ, ?_, ?_, ?_, ?_, ?_⟩

  · rfl

  · intro _σ s s' hStep
    exact False.elim hStep

  · intro s a s' hSafe hAuthorized hStep
    exact False.elim hStep

  · constructor <;> rfl

  · simp [safe]

end E13AdversarialBoundary
end GRBS
