import E17ProposalAuthoritySeparation

namespace GRBS.E23TMCRefinement

open GRBS.E17ProposalAuthoritySeparation

/-
  TMC: Transition-Model Correspondence.

  The implementation's actual state transitions must be contained
  in the transitions permitted by the boundary.
-/
def TMC
    {State : Type}
    (actualStep permittedStep : State → State → Prop) : Prop :=
  ∀ s s', actualStep s s' → permittedStep s s'

/-
  The implementation transition relation generated by the gated
  reference monitor.

  A transition exists iff some proposal, when passed through the
  gate, produces that state transition.
-/
def gatedActualStep (s s' : St) : Prop :=
  ∃ p : Proposal, GatedStep p s = s'

/-
  The boundary-permitted transition relation.

  Authorized proposals may induce their corresponding transition.
  Unauthorized proposals may only produce stuttering.
-/
def permittedStep (s s' : St) : Prop :=
  (∃ p : Proposal,
    authorized (resolve p) = true ∧
    step s (resolve p) = s')
  ∨ s = s'

/-
  The gated implementation is contained in the permitted transition
  relation. This is the first concrete TMC result.
-/
theorem gated_implementation_satisfies_tmc :
    TMC gatedActualStep permittedStep := by
  intro s s' hActual
  rcases hActual with ⟨p, hp⟩
  by_cases hAuth : authorized (resolve p) = true
  · left
    exact ⟨p, hAuth, by
      simp [GatedStep, hAuth] at hp
      exact hp⟩
  · right
    simp [GatedStep, hAuth] at hp
    exact hp

/-
  An ungated implementation directly executes the action selected
  by the proposal.
-/
def ungatedActualStep (s s' : St) : Prop :=
  ∃ p : Proposal, step s (resolve p) = s'

/-
  The ungated implementation does NOT satisfy TMC.

  The execution proposal reaches the compromised state, while the
  permitted relation cannot authorize that transition.
-/
theorem ungated_implementation_fails_tmc :
    Not (TMC ungatedActualStep permittedStep) := by
  intro h
  have htmc :=
    h St.safe St.compromised
      ⟨Proposal.execCode, by simp [resolve, step]⟩
  rcases htmc with hpermitted | hstutter
  · rcases hpermitted with ⟨p, hAuth, hStep⟩
    cases p <;> simp [resolve, authorized, step] at hAuth hStep
  · simp at hstutter

/-
  E23-A experiment:
  the mediated implementation satisfies TMC while the ungated
  implementation fails it.
-/
theorem e23a_tmc_refinement_experiment :
    TMC gatedActualStep permittedStep
    ∧ Not (TMC ungatedActualStep permittedStep) :=
  ⟨gated_implementation_satisfies_tmc,
   ungated_implementation_fails_tmc⟩

end GRBS.E23TMCRefinement
