/-
  DARM Behavioral Transition Congruence

  v0.13.1

  PURPOSE

  Behavioral representation adequacy is a state-level property:

      same representation -> same observed behavior

  This module adds the corresponding transition-level property:

      same representation
        +
      same event
        ->
      same represented successor

  The purpose is to formalize the condition under which a
  representation remains stable under the transition relation.

  This module deliberately uses a total transition function.
  A rejected event is therefore represented by whatever state
  the transition system returns, including an identity/null
  transition when that is the system's semantics.

  No claim is made here that:
    * the transition system models physical reality;
    * the representation is complete;
    * the representation is minimal;
    * transition congruence is sufficient for every guarantee;
    * the event set captures every possible environmental influence.
-/

import DarmMonitor.BehavioralAdequacy

namespace DARM

/--
Transition congruence of a representation.

If two states have the same representation, then applying the same
event to both states must produce states having the same representation.
-/
def TransitionCongruent
    {State Representation Event : Type}
    (ρ : State → Representation)
    (step : State → Event → State) : Prop :=
  ∀ s₁ s₂ e,
    RepresentationEq ρ s₁ s₂ →
    RepresentationEq ρ (step s₁ e) (step s₂ e)

/--
Transition congruence immediately preserves representation equality
across one transition.
-/
theorem transition_congruent_step
    {State Representation Event : Type}
    {ρ : State → Representation}
    {step : State → Event → State}
    (hCongruent : TransitionCongruent ρ step)
    {s₁ s₂ : State}
    {e : Event}
    (hRep : RepresentationEq ρ s₁ s₂) :
    RepresentationEq ρ (step s₁ e) (step s₂ e) := by
  exact hCongruent s₁ s₂ e hRep

/--
A representation satisfying transition congruence preserves
representation equality across every finite event trace.

The fold uses the same event sequence on both states.
-/
theorem trace_representation_preserved
    {State Representation Event : Type}
    {ρ : State → Representation}
    {step : State → Event → State}
    (hCongruent : TransitionCongruent ρ step)
    (es : List Event)
    {s₁ s₂ : State}
    (hRep : RepresentationEq ρ s₁ s₂) :
    RepresentationEq ρ
      (es.foldl step s₁)
      (es.foldl step s₂) := by
  induction es generalizing s₁ s₂ with
  | nil =>
      exact hRep
  | cons e es ih =>
      simp only [List.foldl_cons]
      apply ih
      exact hCongruent s₁ s₂ e hRep

/--
A behaviorally adequate representation remains behaviorally adequate
after a transition step when the behavior observation is evaluated
on the successor state.

This theorem makes the connection between transition congruence and
the existing state-level behavioral adequacy abstraction explicit.
-/
theorem behaviorallyAdequate_after_step
    {State Representation Event Behavior : Type}
    {ρ : State → Representation}
    {step : State → Event → State}
    {B : State → Behavior}
    (hAdequate : BehaviorallyAdequate ρ B)
    (hCongruent : TransitionCongruent ρ step)
    (e : Event) :
    BehaviorallyAdequate ρ (fun s => B (step s e)) := by
  intro s₁ s₂ hRep
  exact hAdequate _ _ (hCongruent s₁ s₂ e hRep)


/--
A bounded future-behavior observation generated by a finite collection
of event traces.

Each supplied trace is executed from the initial state and observed
through `Obs`. The resulting list is the bounded behavioral profile.

The trace collection is an explicit boundary of the observation.
This definition therefore does not claim to quantify over all possible
events or all possible executions.
-/
def boundedTraceBehavior
    {State Representation Event Observation : Type}
    (ρ : State → Representation)
    (step : State → Event → State)
    (Obs : State → Observation)
    (traces : List (List Event))
    (s : State) : List Observation :=
  traces.map (fun es => Obs (es.foldl step s))

/--
If a representation is transition-congruent and behaviorally adequate
for the observation `Obs`, then it is adequate for the bounded
future-behavior profile induced by any supplied finite trace set.
-/
theorem behaviorallyAdequate_boundedTraceBehavior
    {State Representation Event Observation : Type}
    {ρ : State → Representation}
    {step : State → Event → State}
    {Obs : State → Observation}
    (traces : List (List Event))
    (hObs : BehaviorallyAdequate ρ Obs)
    (hCongruent : TransitionCongruent ρ step) :
    BehaviorallyAdequate ρ
      (boundedTraceBehavior ρ step Obs traces) := by
  intro s₁ s₂ hRep
  induction traces generalizing s₁ s₂ with
  | nil =>
      rfl
  | cons es traces ih =>
      simp only [boundedTraceBehavior, List.map_cons]
      have hHead :
          Obs (es.foldl step s₁) =
            Obs (es.foldl step s₂) := by
        exact hObs _ _ (trace_representation_preserved hCongruent es hRep)
      rw [hHead]
      congr 1
      exact ih s₁ s₂ hRep

theorem behaviorallyAdequate_after_trace
    {State Representation Event Behavior : Type}
    {ρ : State → Representation}
    {step : State → Event → State}
    {B : State → Behavior}
    (hAdequate : BehaviorallyAdequate ρ B)
    (hCongruent : TransitionCongruent ρ step)
    (es : List Event) :
    BehaviorallyAdequate ρ
      (fun s => B (es.foldl step s)) := by
  intro s₁ s₂ hRep
  exact hAdequate _ _ (trace_representation_preserved hCongruent es hRep)

end DARM

#print axioms DARM.transition_congruent_step
#print axioms DARM.trace_representation_preserved
#print axioms DARM.behaviorallyAdequate_after_step
#print axioms DARM.behaviorallyAdequate_after_trace
#print axioms DARM.behaviorallyAdequate_boundedTraceBehavior
