#!/usr/bin/env python3
"""docs/MODULES.md, generated: every module in both libraries, described by its
own header comment, with its theorem count and how it is checked. --write
writes the file; --check fails if the file differs from what the code says.
Usage: scripts/modules_index.py --write | --check"""
import glob, os, re, sys

KINDS = ("theorem", "lemma")
DECL = re.compile(r"^\s*(?:@\[[^\]]*\]\s*)*(?:(?:private|protected|noncomputable|nonrec|partial|unsafe|scoped)\s+)*"
                  r"(theorem|lemma)\b")
ACRONYMS = {"DARM", "GRBS", "AG", "TMC", "ODATS", "SACM", "AEB", "LLM", "ABI", "C", "JSON", "CI", "API",
            "IO", "FFI", "CAS", "IC", "DCEE", "PCC", "TCB", "LSM", "BPF", "AI", "I", "II", "III"}
FAMILIES = [   # (prefix test, heading), in reading order; names from the README's own sections
    (lambda m: m.startswith("K") and m[1:2].isdigit(), "Decision kernel and its servers (K)"),
    (lambda m: m.startswith("B") and m[1:2].isdigit(), "Broker models (B)"),
    (lambda m: m.startswith("E") and m[1:2].isdigit(), "Effects, intents and authorization (E)"),
    (lambda m: m.startswith("R") and m[1:2].isdigit(), "Assurance transfer (R)"),
    (lambda m: m.startswith("AG"), "Assume-guarantee (AG)"),
    (lambda m: m.startswith("IC") and m[2:3].isdigit(), "Runtime correspondence (IC)"),
    (lambda m: m.startswith("DCEE"), "Prior-art comparison (DCEE)"),
    (lambda m: True, "Core and other modules"),
]

def strip_comments(src):
    return re.sub(r"--[^\n]*", "", re.sub(r"/-.*?-/", "", src, flags=re.S))

def theorems(src):
    return sum(1 for l in strip_comments(src).split("\n") if DECL.match(l))

def describe(src):
    """The module's own words: the first line of its first block comment, or, when
    that line is an all-caps title, the first sentence of the prose beneath it."""
    m = re.search(r"/-[-!]?(.*?)-/", src, re.S)
    if not m:
        return "(no header comment)"
    paras, cur = [], []
    for line in m.group(1).split("\n"):
        s = line.strip()
        if s:
            cur.append(s)
        elif cur:
            paras.append(" ".join(cur)); cur = []
    if cur:
        paras.append(" ".join(cur))
    paras = [p for p in paras if re.search(r"[A-Za-z]", p)]
    if not paras:
        return "(no header comment)"
    first = m.group(1).strip().split("\n")[0].strip()
    letters = re.sub(r"[^A-Za-z]", "", re.sub(r"\(.*?\)", "", first))   # a parenthesized version aside
    if letters and sum(c.isupper() for c in letters) >= 0.8 * len(letters):
        # an all-caps title: its own words, in sentence case, without the module code
        title = re.sub(r"^[A-Z]{1,5}\d+[a-z]?\b[\s\u2014:-]*", "", first)
        words = []
        for w in title.split():
            core = re.sub(r"[^A-Za-z]", "", w)
            keep = (any(c.isdigit() for c in w) or any(c.islower() for c in w)
                    or core in ACRONYMS)
            words.append(w if keep else w.lower())
        text = " ".join(words)
        text = text[:1].upper() + text[1:]
    else:
        text = paras[0]
    text = re.sub(r"^#+\s*", "", text)                     # a Markdown heading inside the comment
    code = re.match(r"^[A-Za-z]*-?\d[\w-]*(?: [A-Z0-9 \u2014-]+)?:\s+(.+)$", text)   # "B9 RECOVERY CHECK: ...", "R3c: ..."
    if code:
        text = code.group(1)[:1].upper() + code.group(1)[1:]
    sentence = re.split(r"(?<=[.;])\s", text, maxsplit=1)[0]
    sentence = sentence if len(sentence) <= 180 else sentence[:177].rstrip() + "..."
    return sentence.replace("|", "\\|")

def imports(path, known):
    return {x for l in open(path) if l.startswith("import ") for x in l.split()[1:] if x in known}

def closure(roots, imp):
    seen, todo = set(), list(roots)
    while todo:
        m = todo.pop()
        if m not in seen:
            seen.add(m); todo.extend(imp.get(m, ()))
    return seen

grbs = {os.path.basename(f)[:-5]: f for f in sorted(glob.glob("GRBS/*.lean"))}
dm = {}
for d, _, fs in os.walk("DarmMonitor"):
    for f in fs:
        if f.endswith(".lean"):
            p = os.path.join(d, f); dm[p[:-5].replace(os.sep, ".")] = p
if os.path.exists("DarmMonitor.lean"):
    dm["DarmMonitor"] = "DarmMonitor.lean"
dm_imp = {m: imports(p, dm) for m, p in dm.items()}
main_imp = sorted(imports("Main.lean", dm)) if os.path.exists("Main.lean") else []
default = closure(["DarmMonitor"], dm_imp)
demo = closure(main_imp, dm_imp) - default

def entry(name, path, how):
    src = open(path).read()
    return f"| `{name}` | {describe(src)} | {theorems(src)} | {how} |"

out = ["# Module index", "",
       "Every Lean module in the repository, described by its own header comment, with the number of",
       "theorems and lemmas it declares and how continuous integration checks it. Generated by",
       "`scripts/modules_index.py`; the gate fails if this file falls behind the code.", "",
       "How a module is checked: **gate** = built by `scripts/gate.sh` before every push and by CI;",
       "**default build** = built by `lake build` in CI; **darmdemo** = built and run by CI's runtime tier;",
       "**tier 3** = elaborated file by file by CI's complete-corpus tier.", ""]
total_th = sum(theorems(open(p).read()) for p in list(grbs.values()) + list(dm.values()))
out += [f"{len(grbs) + len(dm)} modules, {total_th} theorems and lemmas.", ""]
out += ["## GRBS library", ""]
placed = set()
for test, heading in FAMILIES:
    mods = [m for m in grbs if m not in placed and test(m)]
    if not mods:
        continue
    placed |= set(mods)
    out += [f"### {heading}", "", "| Module | Description | Theorems | Checked by |", "| --- | --- | --- | --- |"]
    out += [entry(m, grbs[m], "gate") for m in sorted(mods)]
    out += [""]
out += ["## DarmMonitor library", "", "| Module | Description | Theorems | Checked by |", "| --- | --- | --- | --- |"]
for m in sorted(dm):
    how = "default build" if m in default else "darmdemo" if m in demo else (
          "tier 3" if m.count(".") == 1 else "**not checked by CI**")
    out.append(entry(m, dm[m], how))
text = "\n".join(out) + "\n"

if "--write" in sys.argv:
    os.makedirs("docs", exist_ok=True)
    open("docs/MODULES.md", "w").write(text)
    missing = sum(1 for l in out if "(no header comment)" in l)
    print(f"docs/MODULES.md: {len(grbs) + len(dm)} modules, {total_th} theorems; {missing} without a header comment")
elif not os.path.exists("docs/MODULES.md") or open("docs/MODULES.md").read() != text:
    print("docs/MODULES.md is out of date; run scripts/modules_index.py --write")
    sys.exit(1)
else:
    print("docs/MODULES.md matches the code")
